### ISSUE TITLE
Incompatibility with SkinLayers3D

### ISSUE THREAD

**Issue by MechanicalDragon0687** [Sintinium/oauth#10]
https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d

crashes during rendering when opening the client screen.

https://pastebin.com/d9DYEZE3

**Comment by Sintinium** [comment]
They're using mixins so I can't quickly put out a fix for this. I'm going to remove/replace this feature. I should have it fixed within a day or two. Sorry about that.

**Comment by Sintinium** [comment]
I rewrote the way rendering the player works so there shouldn't be any mods that ever break it again. I checked and it fixes compatibility with SkinLayers3D!

**Comment by MechanicalDragon0687** [comment]
Fantastic! Keep up the great work, I really appreciate your quick response and continued dedication to this project.
