### ISSUE TITLE
Adding "OAuth Login" to main-menu with "PackMenu" mod

### ISSUE THREAD

**Issue by bradcarnage** [Sintinium/oauth#11]
utilizing [PackMenu](https://github.com/Shadows-of-Fire/PackMenu/wiki/PackMenu-Button-Schema), would it be possible to move this button to the main menu?

**Comment by Sintinium** [comment]
I'm not familiar with adding things to packmenu but I'll see what I can do

**Comment by Sintinium** [comment]
After looking through their wiki and code PackMenu doesn't have an api for other mods. So until they add support there's not much I can do.
