### ISSUE TITLE
OAuth doesnt work in ATM6

### ISSUE THREAD

**Issue by ChapperNi** [Sintinium/oauth#12]
![image](https://user-images.githubusercontent.com/39083272/147614760-dcd4088e-be6c-4b47-ada0-6981b639b83c.png)
[latest.log](https://github.com/Sintinium/oauth/files/7786723/latest.log)

**Comment by Sintinium** [comment]
I'm unable to reproduce this using the latest version on both ATM6 and OAuth. Does it work once then give this error when trying to login again? Or is it even on the first time? If it does it after the 2nd time it's an issue on my end but if it's the first time it's another program on your computer using that port.

If it's on the first time could you do the following whenever it gives you that error again?

- Click the windows key
- Type in 'powershell' and open Windows PowerShell
- Paste in `Get-Process -Id (Get-NetTCPConnection -LocalPort 29996).OwningProcess`

After that send a screenshot of what it says. This will tell me the programs that binds to the same port.

**Comment by Sintinium** [comment]
Feel free to reopen this issue if it's not fixed :)
