### ISSUE TITLE
Please move profile location to root of minecraft directory

### ISSUE THREAD

**Issue by LatvianModder** [Sintinium/oauth#13]
What title says. Keeping the file that *contains your tokens* in `./config/oauth/profiles.json` is very annoying for pack devs, as they might accidentally ship that file with their pack when exporting it. Same if they work with git when developing pack. You should move it to `./oauthprofiles.json`. It also means that the file in config folder most likely gets overriden every time pack updates by launcher.

**Comment by Sintinium** [comment]
I originally put it in the config folder since reauth and others did it but I'll definitely move it. I'll try to have the update out tomorrow. Thanks for the feedback.

**Comment by LatvianModder** [comment]
Thanks!
