### ISSUE TITLE
[ISSUE] "Error logging into Mojang. Wrong Password" [Forge, v1.18.1]

### ISSUE THREAD

**Issue by sdarkwell** [Sintinium/oauth#14]
**Hello!**

I have attempted to use OAuth, but it have yet to successfully use it to re-authenticate my Client. Attempting to re-validate my Mojang account, it displays the error "Error logging into Mojang. Wrong Password. Please delete the profile and create a new one."

I've attempted to use it on a number of Forge. Below are the steps I can use via GDLauncher to create a new Minecraft instance and recreate the error. I've also tried using OAuth in non-test cases and have yet to have it successfully log in.

**Recreating the error from scratch:**
1. Start GDLauncher application
2. Create a brand new Forge instance of Minecraft v1.18.1 within GDLauncher (leaving all settings as default)
3. (Wait for installation to complete)
4. Start Minecraft instance via GDLauncher
5. (Wait for Minecraft to start)
6. Click [Multiplayer] button
7. Click [Proceed] button to continue through "Caution: Third-Party Online Play" notice
8. Click [OAuth Login] button
9. Click [Add Account] button
10. Click [Mojang Login] button
11. Enter Username
12. Enter Password
13. Click [Add Profile] button
14. (Returns to the "Current Profile" screen and shows "Status: Online, Current Profile: S_Darkwell")
15. Click [Login] button (with "S_Darkwell" selected by default)
16. (Displays error, "Error logging into Mojang. Wrong Password. Please delete the profile and create a new one.")

**Additional troubleshooting performed**
- Confirmed credentials by logging into Mojang website
- "Logging Offline" with OAuth, closing Minecraft, GDLauncher, rebooting, and starting the Minecraft instance again following reboot
- Adding exceptions and disabling all firewall software
- Adding exceptions and disabling all anti-virus software
- Though uncertain of the expected results, I also executed the PowerShell code per recommendation in "#12", which resulted in the message "No MSFT_NetTCPConnection objects found with property 'LocalPort' equal to '29996'.  Verify the value of the property and retry." (see image below) ![WindowsPowershell](https://user-images.githubusercontent.com/17504940/147970496-3a32ae2d-0a22-433c-9656-363e26e9f897.png)

**Version Info:**
- OAuth (v1.1.7-1.18.1)
- Minecraft: v1.18.1
- Forge: v39.0.10
- Java: v17.0.1+12
- GDLauncher: v1.1.21
- Windows: Windows 10 Pro 20H2 19042.1415

Apologies if there is anything I may have overlooked. Please let me know if there is anything else I can provide to help or any troubleshooting steps that I can perform.

**Thank you and be well!** :)
\- S.

**Comment by Sintinium** [comment]
I'm not entirely sure what's wrong so I just updated the mod to 1.1.8 to print all login errors to the log file. If you don't care could you update and try logging in again? Once it gives you the error screen send me your log file. Thanks!

**Comment by sdarkwell** [comment]
**Hello @Sintinium,**

Thank you for the quick response!

Alas, now the login simply says "Loading" (continuously cycling between 0 and 3 periods after the word). It never actually fails or displays an error message.

Here is my log file, though!
- [latest.log](https://github.com/Sintinium/oauth/files/7805215/latest.log)


I am about to go offline for the evening, but will be happy to provide any additional help that I can come morning.

**Thank you so much again and be well!**
\- S.

**Comment by Sintinium** [comment]
I appreciate you helping! I've looked over the code multiple times now and I don't see a way to fix it. I'm just calling minecraft's built in login method. It *should* eventually either log you in or throw an error. I'm sorry this is happening!

One more thing I recommend is trying ReAuth on curseforge. If it works for you would you care to let me know here? Because if it works and mine doesn't then it's 100% my fault

**Comment by sdarkwell** [comment]
**Hello @Sintinium,**

I'm happy to help!

ReAuth isn't compatible with Minecraft v1.18.1 (I tried), but I was able to log in using ReAuth on a Minecraft v1.16.5 instance without any issues.

Using OAuth on v1.16.5, just like before it remained on the "Loading..." screen for a long while. After 11 minutes, no error messages displayed in the Client, but it did post to the "latest.log" file.

**I've attached that "latest.log file" below:**
- [latest.log](https://github.com/Sintinium/oauth/files/7826384/latest.log)

In this case, I created a brand new Minecraft v1.16.5 instance, logged in, purposely entered incorrect credentials. After being provided an error that my credentials were incorrect, I proceeded to provide the correct ones. Finally, I added the account, then clicked the [Login] button from the "Current Profile" screen, where it has been loading every since.

The log actually contains a NullPointerException error, so hopefully this log will prove more helpful!

**Thank you again, and be well! :)**
\- S

**Comment by Sintinium** [comment]
Sorry for the late response I've been busy. Comparing my code to ReAuth's I don't see where it could go wrong. I could send you a debug version of the mod that'd log everything to try and narrow it down if you want. 

https://www.dropbox.com/s/avgxlcnrvhhvpsd/oauth-1.1.8-1.18.1.jar?dl=1

Just download that and put it in your mod's folder (in 1.18.1) and login normally. It should log everything. Wait until it takes you to the multiplayer screen (or after like 10 seconds) and then send me your latest log. Thanks for your help :)

**Comment by sdarkwell** [comment]
**Hello @Sintinium,**

No to worry. These things happen!

**Here is the "latest.log" file:**
- [latest.log](https://github.com/Sintinium/oauth/files/7918651/latest.log)

**Also, not certain what changed, but I received an error on-screen this time:**
![image](https://user-images.githubusercontent.com/17504940/150645544-24422e56-1edf-4e1e-8300-9bc7565ad486.png)

Hopefully these details will help.

**Thank you and be well!**
\- S.

**Comment by Sintinium** [comment]
Yeah I figured it'd give an error screen because of the way I did it. But now I'm even more confused because it didn't even log the part I needed haha.

https://www.dropbox.com/s/5llxm9bmhmqcdvz/oauth-1.1.8-1.18.1-DEBUG.jar?dl=1

Try this version? If it doesn't work then I'm completely out of ideas

**Comment by sdarkwell** [comment]
**Hello @Sintinium,**

Weird!

Here's the log from the new version:
- [latest.log](https://github.com/Sintinium/oauth/files/7919273/latest.log)

Hopefully that's more useful!

**Thank you and be well!**
\- S.

**Comment by Sintinium** [comment]
I honestly don't even know how it's possible that it's not generating a proper log. The only thing I can think of is the mojang auth api is throwing an error but not printing it out anywhere. I'll continue to look for a solution but until I figure out *what's* causing it there's not much I can do.

**Comment by Sintinium** [comment]
Could you send me your debug.log if you have one after the issue happens? If 1.18 doesn't give you a debug.log try using oauth on the 1.16 version and it should. Looking through mojang's code it should actually give me the logs I need

**Comment by sdarkwell** [comment]
**Hello @Sintinium,**

Unfortunately, neither v1.16 nor v1.18 are generating a "debug.log" file. :(

Is there anything else that I might be able to ensure one generates?

**Thank you and be well!**
\- S.

**Comment by Sintinium** [comment]
After looking through mojang's code I don't think the debug.log will have what I need sadly. So on the latest version (not one I sent here the one on curseforge) it still just loads forever? Or does it tell you the original message? If it tells the original message send your log with that. Sorry to keep going in loops but I just realized I never got the logs for the original problem

**Comment by sdarkwell** [comment]
Hello @Sintinium,

Not to worry! I'm a software developer myself (not related to Minecraft), and I understand how difficult it can be to troubleshoot issues without users' help.

Running the latest Minecraft v1.18.1 Curseforge version of OAuth, there are the details:
- [latest.log](https://github.com/Sintinium/oauth/files/7936799/latest.log)

![image](https://user-images.githubusercontent.com/17504940/151051385-18d91e9c-ae83-4ef5-a6f8-a90a1a32f517.png)

Although I acknowledge you said that the debug.log likely wouldn't help, I thought it might be useful to know that no debug.log was ever generated.

Hope that helps! Please let me know if there is anything else I can provide to assist.

**Thank you and be well! :)**
\- S.

**Comment by Sintinium** [comment]
That log file is from one of the versions I sent you here which purposely freezes the login thread so I could dump the threads. You might have to manually delete the mod and redownload it

**Comment by sdarkwell** [comment]
**Hello @Sintinium,**

Apologies! I thought I was using a new Minecraft instance, but apparently I had unintentionally used an old one.

This time, it never displayed an error. Here is the log:
- [latest.log](https://github.com/Sintinium/oauth/files/7942598/latest.log)

**Thank you and be well!**
\- S.

**Comment by Sintinium** [comment]
So it's working now? Or is it still not logging you in

**Comment by sdarkwell** [comment]
**Hello @Sintinium,**

Apologies for the lack of clarity. It's still not working–it never logs in.

I attempted to log in, left it on the "Loading..." screen for approximately 12 minutes, then quit.

**Thank you and be well!**
\- S.

**Comment by Sintinium** [comment]
https://www.dropbox.com/s/q86wgivpnoewppi/oauth-Custom-Auth-1.18.1.jar?dl=1

Try this 1.18.1 version. I wrote my own login handler instead of using minecraft's built in one.

**Comment by sdarkwell** [comment]
**Hello @Sintinium,**

It's not letting me add an account.

When I attempt to add a profile, after completing the "Username/Email" and "Password" fields, I click the [Add Profile] button, and nothing happens. There is no detectable delay and the screen remains unchanged. It doesn't freeze, it just acts like I never clicked it, except that the field loses focus.

I checked the latest.log, and there was no output whatsoever.

I then tried purposefully entering the incorrect password. In that case, there _was_ output in the latest.log, but the screen similarly didn't react at all.

Also, one small bug that I've noticed with this and prior versions is that after clicking on [Add Account], then the [Mojang Login] button, although the cursor is in the "Username/Email" field, it seems to not actually be in focus; typing does nothing. Users must click the field to focus it before typing. Obviously, not at all a serious bug, but figured I would mention it as well!

**Thank you and be well!**
\- S.

**Comment by Sintinium** [comment]
https://www.dropbox.com/s/h0pe3epna7hryon/oauth-Custom-Auth-2-1.18.1.jar?dl=1

Try this one and see? If it doesn't give any logs then I'm missing something. I really appreciate you helping and bearing with me.

Thanks for the report on the username/password fields I'll get that fixed on the next public version

**Comment by sdarkwell** [comment]
**Hello @Sintinium,**

Of course! Hopefully it helps.

This time I received an error trying to create an account, which is unusual. I am usually able to create the account, but receive the error (if any) when trying to log in.

![image](https://user-images.githubusercontent.com/17504940/151616025-08f259c4-94b1-415d-a126-39deb7545a4c.png)

I tried creating my profile twice, which the latest.log did capture:
- [latest.log](https://github.com/Sintinium/oauth/files/7961688/latest.log)

Hopefully that log is a bit more useful.

**Thank you and be well!**
\- S.

**Comment by Sintinium** [comment]
https://www.dropbox.com/s/6mhj5hbr5hzdiz8/oauth-custom-auth-3-1.18.1.jar?dl=1

Ok this should be the last special version I'll need you to use. That log helps a ton and I think I might know the issue but the new version will let me know 100%

**Comment by sdarkwell** [comment]
**Hello @Sintinium,**

Awesome!

Here are the details:
![image](https://user-images.githubusercontent.com/17504940/151663891-98ef4d6d-6114-43d5-b996-a81996a4c8b6.png)

Log:
- [latest.log](https://github.com/Sintinium/oauth/files/7963822/latest.log)

Also, it looks like you already fixed the inability to type into the "Username/Email" field without first clicking on it. Nice!

**Hope this help! Thank you and be well. :)**
- S.

**Comment by Sintinium** [comment]
https://www.dropbox.com/s/xrz9qcl4940n4gq/oauth-custom-auth-4-1.18.1.jar?dl=1

That's really strange. I don't see why it gives an error when you actually login. Try this version. Also for some odd reason your account is missing data. It's not important but was one of the original reasons it loaded forever

**Comment by sdarkwell** [comment]
Hello @Sintinium,

Huh! That's interesting! What information is my account missing? I won't change anything–I'm just curious!

The latest errors:
![image](https://user-images.githubusercontent.com/17504940/151666113-7643142c-9aac-4a21-926c-41688adb5c0f.png)

- [latest.log](https://github.com/Sintinium/oauth/files/7963963/latest.log)

The log mentions invalid credentials, but I just confirmed via logging into both https://account.mojang.com/login and https://www.minecraft.net that my credentials are correct.

Probably a completely irrelevant question, but is it possible that certain special characters in passwords are not being interpreted properly?

Also, I've located another bug: After selecting an account and removing it, it is removed from the list, but the [Remove] button remains enabled. If you click the [Remove] button again (this time with no account selected), Minecraft crashes.
- [latest.log](https://github.com/Sintinium/oauth/files/7963979/latest.log)

**Thank you and be well!**
\- S.

**Comment by Sintinium** [comment]
Ok I've finally figured out the problem. I'm storing the username instead of the email. Unfortunately I can't work on it anymore today but I'll try to have a fix out as soon as I can. And thanks for the report I'll be sure to fix it too

**Comment by sdarkwell** [comment]
**Hello @Sintinium,**

That's great news! Not to worry. I look forward to the update, whenever you have a chance to publish it.

Happy to help.

**Thank you and be well!**
\- S.

**Comment by Sintinium** [comment]
https://www.dropbox.com/s/w1w7id75m0elhrx/oauth-1.1.12-1.18.1.jar?dl=1

Hey before releasing the fix I just wanted to make sure this actually fixes the problem. Would you care to try this version and let me know if it finally solves the issue? Thanks!

**Comment by sdarkwell** [comment]
**Hello @Sintinium**

It certainly seems to! Obviously, I can't test whether it allows me to log back in after timing out without a significant amount of time passing, but it appears to recognize and accept my credentials. Awesome!

**I did notice that this error still occurs, though:**
> After selecting an account and removing it, it is removed from the list, but the [Remove] button remains enabled. If you click the [Remove] button again (this time with no account selected), Minecraft crashes.

Aside from that, it seems perfect!

**Thank you so much and be well. :)**
\- S.

**Comment by Sintinium** [comment]
Glad to hear! Thanks for all your help! And oh yeah thanks for reminding me of that bug I actually forgot about it. I'll leave this issue open as a reminder until I fix it.

**Comment by sdarkwell** [comment]
**Hello @Sintinium,**

Hey, happy to help! Thank you for taking the time to track down the issue and fix it! :)

**Thanks again! Be well!**
\- S.
