### ISSUE TITLE
Cannot add Microsoft account

### ISSUE THREAD

**Issue by Gamemaster4715** [Sintinium/oauth#15]
[latest.log](https://github.com/Sintinium/oauth/files/7908639/latest.log)

**Comment by Sintinium** [comment]
I'm not sure if Microsoft changed the api or what but I'll look into it. Thanks for the report

**Comment by Sintinium** [comment]
I believe this was an issue on Minecraft's side after doing some digging. Can you try again and see if the issue still happens? Thanks.

**Comment by Gamemaster4715** [comment]
I tried again and unfortunately, it still didn't work, if this helps the account I was adding was a different account than I was signed into on my client.
[latest.log](https://github.com/Sintinium/oauth/files/7918928/latest.log)

**Comment by Sintinium** [comment]
Is the accounts date of birth under 18 years old?

**Comment by Gamemaster4715** [comment]
Yes.

**Comment by Sintinium** [comment]
Sadly their api doesn't allow accounts under 18 to use 3rd party logins for some reason. So I believe you either need to change the age if you can or setup a family group on an adult account. In the next update I'll add a warning to let people know
