### ISSUE TITLE
Custom MS Azure 

### ISSUE THREAD

**Issue by Sapu98** [Sintinium/oauth#2]
Hello, this is not a real issue, I just wanted to know how did you setup your Azure application to get this to work with your id.
I tried creating a new application id but if I replace yours with mine I get this: 
"invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application."

**Comment by Sintinium** [comment]
You have to set the redirect uri in your app to the same as oauth uses
