### ISSUE TITLE
Cannot log in with Mojang Account 1.18.1

### ISSUE THREAD

**Issue by Zieg777** [Sintinium/oauth#23]
Running oauth-1.1.11-1.18.1.jar

Tells me that I already moved to a microsoft account. I havent yet.
[latest.log](https://github.com/Sintinium/oauth/files/8033316/latest.log)

**Comment by Zieg777** [comment]
I should add, This is forge

**Comment by Sintinium** [comment]
Does your account use an email to login? If so it's currently broken and I'm currently working on it

**Comment by Sintinium** [comment]
https://www.minecraft.net/en-us/article/last-call-voluntarily-migrate-java-accounts

Closing this since after March 10th mojang accounts will no longer work
