### ISSUE TITLE
Can't log in for microsoft account "An Error occured" Divine Journey 2 - 1.12.2 Java Modpack that uses OAuth 1.06.2 jar

### ISSUE THREAD

**Issue by wizard1peter** [Sintinium/oauth#25]
When I click log in with Microsoft Account, I click a Microsoft account that has bought Minecraft and it says I can close my browser, but when I go back to Minecraft it says an error occurred.
![image](https://user-images.githubusercontent.com/100010507/154786027-050d44d3-2aa0-4f9f-b2a0-825f8f8e2679.png)

**Comment by Sintinium** [comment]
I haven't backported the changes to 1.12.2 yet but my guess is your accounts date of birth is under 18. Which is a Microsoft requirement for 3rd party logins. Try changing the account age and let me know if that fixes it

**Comment by xJon** [comment]
Would love to have the changes backported to 1.12.2 for the mod to be added to [Hexxit II](https://www.technicpack.net/modpack/hexxit-ii.896745/)!

**Comment by Sintinium** [comment]
Should be fixed in the latest release
