### ISSUE TITLE
Error occured while sign in with Microsoft Account.

### ISSUE THREAD

**Issue by M3veronMast3r** [Sintinium/oauth#28]
It just says i have to add the log file to this issue post. so here it is
[debug.log](https://github.com/Sintinium/oauth/files/8237837/debug.log)
![Screenshot01](https://user-images.githubusercontent.com/85065686/158024031-fab906e6-5fac-4d62-b869-889ebf7e0912.png)
:
i hope it will get fixed soon. i used the newest 1.16.5 version of oauth with minecraft forge 36.2.30

**Comment by DrLee-lihr** [comment]
may duplicate #27 
also i got the same exception in Forge 1.16.5

**Comment by Sintinium** [comment]
Yeah this is a duplicate. But what Java version are you using? It should be the first few lines of your log file. I need the number and publisher (usually oracle)

**Comment by M3veronMast3r** [comment]
@Sintinium the Newest Version of Java 8 64bit for win7
