### ISSUE TITLE
Microsoft login error

### ISSUE THREAD

**Issue by ghost** [Sintinium/oauth#33]
[latest.log](https://github.com/Sintinium/oauth/files/8424474/latest.log)
Crashes when trying to login to Microsoft account. Webpage says that i can close the webpage after which an enormous error message appears on my minecraft screen:
![image](https://user-images.githubusercontent.com/77120663/161916341-92c89b34-4d5b-4c7a-b462-9276b9ee5ff5.png)
Greetings,

**Comment by ghost** [comment]
Its on 1.12.2 Forge btw, forgot to mention that

**Comment by Sintinium** [comment]
This is a bug from Mojang changing the certs in the java version they use. I still haven't backported the fix from 1.12. I'll try to get it as soon as I can

**Comment by Sintinium** [comment]
Could you update to the most recent version and let me know if the issue is fixed?
