### ISSUE TITLE
Socket closed on login

### ISSUE THREAD

**Issue by iCraft85** [Sintinium/oauth#38]
So I keep having this error occur when I am trying to log into my account. Note my status is offline at the time and was hoping that loging in would cause it to become online.
It asked me to put my log file here.

Not sure which of the ones to put so I am putting [debug.log](https://github.com/Sintinium/oauth/files/9034811/debug.log) and my [latest.log](https://github.com/Sintinium/oauth/files/9034812/latest.log).

Not sure if this helps but I am running NTC2.

**Comment by Sintinium** [comment]
Does this issue still happen? Looking at the logs you may have been offline because other mods were throwing the same errors

**Comment by Sintinium** [comment]
If this is still an issue feel free to reopen. I can't reproduce the issue. Thanks!
