### ISSUE TITLE
1.17.1 Forge release?

### ISSUE THREAD

**Issue by Gunner76th** [Sintinium/oauth#4]
I tried looking but have not seen any information regarding this, but is there intent to update to 1.17.1 for Forge? At present there are no ReAuth type mods for 1.17.1 on the Forge system, only Fabric.

**Comment by Sintinium** [comment]
There's already a 1.17 version on curseforge. I'm not sure if it works with 1.17.1 though. If not I'll update it either tonight or tomorrow

**Comment by Gunner76th** [comment]
Strange, it doesnt show up until you do the "View All" then do the drop menu to select a specific version. It also does not show up in mod launchers such as GDLauncher.

**Comment by Gunner76th** [comment]
I can confirm that the current version that is on Curseforge, oauth 1.06-1.17 does work without issue in the following environment: 

![image](https://user-images.githubusercontent.com/5566872/139950711-abfc681f-25aa-4433-a3b6-a8aacd0f76c3.png)

**Comment by Sintinium** [comment]
Ok I'll have to set it on curseforge to support 1.17.1

**Comment by Sintinium** [comment]
Huh it was already set to 1.17.1 that's weird. I'll see what I can do but it seems to be curseforge's fault. Thanks for letting me know about it
