### ISSUE TITLE
"Failed to login: null"

### ISSUE THREAD

**Issue by SpokenWig620933** [Sintinium/oauth#44]
Recently OAuth has just been giving me this ^ error in this modpack whenever I try to connect to my server.

**Comment by MystiaTech** [comment]
I, too, am having this issue. Is there anything chance of this getting fixed since this issue has been open for a month?

**Comment by SpokenWig620933** [comment]
Only if the Author actually decides to care for his project.
For now though, ReAuth isn't as pretty with the menu but does work last I checked.

**Comment by Sintinium** [comment]
So sorry for the delay. I tried fixing this a while back and couldn't figure out the issue. I'll try to have it updated on curseforge for all versions pretty soon.

**Comment by xJon** [comment]
@Sintinium This issue also affected 1.12 a lot so it might be useful to consider.
