### ISSUE TITLE
Microsoft login failure 1.18.2

### ISSUE THREAD

**Issue by thblackdeath38** [Sintinium/oauth#50]
I´m playing Stoneblock 3 with the FTB Launcher and i can´t use Reauth or Oauth.
On Reauth there was not even an error it just did not let me login and join servers.
Oauth at least gave me this. But no clue at all how to fix this one 
![Screenshot_1259](https://user-images.githubusercontent.com/66438175/204034285-207df1e0-6b0c-471e-bf76-e7ebda7071b5.png)

**Comment by Sintinium** [comment]
Try updating to the latest version of oauth

**Comment by thblackdeath38** [comment]
does not work.
newest version auf Reauth does not work at all( no error no nothing the game just closes)

**Comment by thblackdeath38** [comment]
[latest.log](https://github.com/Sintinium/oauth/files/10147516/latest.log)

**Comment by Sintinium** [comment]
Looks like an internet related issue if neither are working. Without knowing your exact setup I can't really help.
