### ISSUE TITLE
not working and crash

### ISSUE THREAD

**Issue by SeamedSiren** [Sintinium/oauth#51]
i tried to join a friends server but my account dont want to be auth 
[console.log](https://github.com/Sintinium/oauth/files/10305701/console.log)
[debug-5.log.gz](https://github.com/Sintinium/oauth/files/10305702/debug-5.log.gz)

**Comment by Sintinium** [comment]
Does it still happen? Looks like a connection issue

**Comment by SeamedSiren** [comment]
yes it still happen 
![image](https://user-images.githubusercontent.com/110154287/209720862-5761c392-c3f6-4cc7-b44f-73eee4fd734b.png)

**Comment by Sintinium** [comment]
Should be fixed in latest version. Feel free to reopen if it's not :)
