### ISSUE TITLE
have this pop up when i try to login us this mod on all the forge 9

### ISSUE THREAD

**Issue by knight793** [Sintinium/oauth#53]
![Capture](https://user-images.githubusercontent.com/111633094/232218726-4db9cb96-62a0-4d70-91ba-e40d92992ef8.PNG)
any help

**Comment by Sintinium** [comment]
Is this still an issue? Sometimes it goes away on it's own if it was a server issue

**Comment by Sintinium** [comment]
I believe this issue is now fixed in the latest version. Feel free to reopen if it persists
