### ISSUE TITLE
It says i cant log into microsoft despite trying too this error code caem up? im playing FTB anniversary

### ISSUE THREAD

**Issue by JackTheCat46** [Sintinium/oauth#55]
[2023-04-21-2.log.gz](https://github.com/Sintinium/oauth/files/11374772/2023-04-21-2.log.gz)

![](https://cdn.discordapp.com/attachments/995077897536675941/1102972323088310294/image.png)

**Comment by JackTheCat46** [comment]
I also just got a different error code just come up after getting pinged back and forth trying to log into my microsoft account
![](https://cdn.discordapp.com/attachments/995077897536675941/1102977635996401724/image.png)

**Comment by Sintinium** [comment]
I think that's an outdated version. Could you try updating and see if the issue persists?

**Comment by JackTheCat46** [comment]
Im sorry to be that old guy XD ,but how can i go about updating it ?

**Comment by JackTheCat46** [comment]
Its all good thank you i refreshed the cache and it was all sorted thank you.
