### ISSUE TITLE
Bug/Error

### ISSUE THREAD

**Issue by SighFor** [Sintinium/oauth#6]
Currently I am running the 1.12.2 version of OAuth and when clicking Microsoft Login it opens a window but still leaves me offline, is this a client error or something to do with the code?

**Comment by Sintinium** [comment]
I believe this is an issue with the older version. I'll try to backport the new updates when I can. Sorry about that

**Comment by Sintinium** [comment]
Ok, this issue should be fixed in the latest release. If not please create another issue with the error text it gives you :)

https://www.curseforge.com/minecraft/mc-mods/oauth/files/3539591
