### ISSUE TITLE
Crash, clien-side, latest 1.16.5 version

### ISSUE THREAD

**Issue by decaductor** [Sintinium/oauth#7]
New Crash report, unable to log in on OAuth in-game, when I click in the button to log in it crashes: https://pastebin.com/sV2DFL2J

**Comment by Sintinium** [comment]
Thanks for the report! Looks to be an incompatibility with hats. I'll try and fix that as soon as I can

**Comment by Sintinium** [comment]
The fix is now up on CurseForge :)
