### ISSUE TITLE
OAuth Incompatible with ToroHealth Mod

### ISSUE THREAD

**Issue by Dark-Arcana** [Sintinium/oauth#8]
SmashingModsTogether/SMT-Issues#27

When pressing the OAuth button in the multiplayer screen in game, the game will crash. This is due to a null pointer exception when rendering the OAuth fake player entity due to an incompatibility with the ToroHealth mod. Refer to the above link for context and stack traces.

**Comment by Sintinium** [comment]
Thanks, I'll get a fix out as soon as I can. I might remove that feature if I can't find a more permanent fix for incompatibilities

**Comment by Dark-Arcana** [comment]
Thanks! I'll keep an eye out for the update and let you know if there are any more issues.

**Comment by Sintinium** [comment]
The latest version on CurseForge fixes this issue :)

**Comment by Dark-Arcana** [comment]
I've tested and confirmed that it is indeed fixed. Thanks for the quick help!
