### ISSUE TITLE
[Enhancement/Request] Allow disabling of player rendering

### ISSUE THREAD

**Issue by MechanicalDragon0687** [Sintinium/oauth#9]
Having seen multiple issues with rendering the fake player, and the fact that i never use this feature, i would appreciate the option to disable the rendering code completely.

A boolean config option would be nice, Thanks

**Comment by Sintinium** [comment]
I've decided in the next update I'm either writing this feature in a way that'll never have incompatibilities (No longer use mojang's  code) or just removing it altogether.

**Comment by Sintinium** [comment]
Ok the rewrite is up and it shouldn't have these issues again so for now I'm not including a config option
